### ISSUE TITLE
Советую заменить на относительный путь

### ISSUE THREAD

**Issue by MaximChshelokov** [Hook10/courseproject#1]
https://github.com/Hook10/courseproject/blob/f3e771c41c3a440cc1a426b5cc414207eedd9040/src/main/java/connectionpool/DBUtil.java#L24

**Comment by Hook10** [comment]
Попытался заменить на относительный путь. К сожалению, проект выдает ошибку. В итоге сделал константу с абсолютным адресом.
properties.load(new FileInputStream(DB_PATH_TO_PROPERTIES));

**Comment by MaximChshelokov** [comment]
Google -> load properties from classpath

**Comment by Hook10** [comment]
Максим, благодарю! Все получилось, все  работает.

**Comment by MaximChshelokov** [comment]
Супер!
