### ISSUE TITLE
Все методы для внутреннего использования рекомендуется делать приватными

### ISSUE THREAD

**Issue by MaximChshelokov** [Hook10/courseproject#10]
https://github.com/Hook10/courseproject/blob/f3e771c41c3a440cc1a426b5cc414207eedd9040/src/main/java/dao/impl/CustomerDaoImpl.java#L102

**Comment by Hook10** [comment]
Добрый день!
Максим,
Спасибо за Вашу помощь в приведении моего проекта к нормальному состоянию!
Скажите, пожалуйста, после внесения всех корректировок мне нужно будет
повторно отправить проект Вам?

Спасибо!

  --
*best regards,*
*Sapashov Askar*
*mob. 8(705)8846688*
*email. sapasask@gmail.com <sapasask@gmail.com>*

вт, 30 июн. 2020 г. в 14:46, MaximChshelokov <notifications@github.com>:

**Comment by Hook10** [comment]
Done
