### ISSUE TITLE
Рекомендуется пользоваться статическим анализатором. Если используете IDEA - Analyze -> Inspect code.

### ISSUE THREAD

**Issue by MaximChshelokov** [Hook10/courseproject#17]
[Hook10.zip](https://github.com/Hook10/courseproject/files/4865049/Hook10.zip)
Сгенерировал вам список замечаний статического анализатора. Не то, чтобы все эти замечания критические, но их количество указывает на возможные проблемы с кодом, так что советую пройтись по всем замечаниям и решить, что можно сделать, чтобы их исправить.

**Comment by Hook10** [comment]
ок, спасибо, поправлю
