### ISSUE TITLE
Хорошим тоном считается давать пакетам, классам, методам и т.д. имена, соответствующие их содержанию и функционалу.

### ISSUE THREAD

**Issue by MaximChshelokov** [Hook10/courseproject#18]
courseproject/src/main/java/connectionpool/
Пакет в данном случае называется connection pool (почитайте про пул), но пула, как такого нет, есть data source

**Comment by Hook10** [comment]
Это же Hikari connection pool https://www.youtube.com/watch?v=6dWfoiZyzJA
Сделал по этому видео уроку.

**Comment by MaximChshelokov** [comment]
Ок, закрываю.
