### ISSUE TITLE
Хорошей идеей будет создать методы isNotValid...

### ISSUE THREAD

**Issue by MaximChshelokov** [Hook10/courseproject#19]
![Screenshot_20200706_090335](https://user-images.githubusercontent.com/35214358/86551943-5615e180-bf68-11ea-8854-197134df35b0.png)
Как правильно подсказывает idea, данный метод везде используется с инверсией (not или !). Поэтому для повышения читаемости кода можно сразу заложить этот not в логику метода, и добавить в его название этот not (isNotValidEmail например)

**Comment by Hook10** [comment]
Done
