### ISSUE TITLE
Неплохо бы записать ошибку в лог

### ISSUE THREAD

**Issue by MaximChshelokov** [Hook10/courseproject#2]
https://github.com/Hook10/courseproject/blob/f3e771c41c3a440cc1a426b5cc414207eedd9040/src/main/java/connectionpool/DBUtil.java#L39

**Comment by MaximChshelokov** [comment]
https://github.com/Hook10/courseproject/blob/f3e771c41c3a440cc1a426b5cc414207eedd9040/src/main/java/encoder/HashFunction.java#L19

**Comment by Hook10** [comment]
Исправлено.

**Comment by Hook10** [comment]
Done.
