### ISSUE TITLE
При создании объекта логгера настоятельно рекомендуется указывать класс, в котором он используется.

### ISSUE THREAD

**Issue by MaximChshelokov** [Hook10/courseproject#24]
https://github.com/Hook10/courseproject/blob/578614eb55d8c0f5e6db8665e73fbad50271c7db/src/main/java/action/actionImpl/PayInvoiceButtonAction.java#L26
Это помогает не запутаться при отладке приложения и чтения логов.

**Comment by Hook10** [comment]
Done
