### ISSUE TITLE
Можно записать объявление переменной и присвоение значения в одну строчку

### ISSUE THREAD

**Issue by MaximChshelokov** [Hook10/courseproject#26]
https://github.com/Hook10/courseproject/blob/578614eb55d8c0f5e6db8665e73fbad50271c7db/src/main/java/action/actionImpl/ShowAllSuppliersAction.java#L29
Здесь и ещё в нескольких экшенах

**Comment by Hook10** [comment]
Поправил во всех методах подобные ошибки.

**Comment by Hook10** [comment]
Done
