### ISSUE TITLE
Запись с помощью оператора switch выглядела бы более лаконично.

### ISSUE THREAD

**Issue by MaximChshelokov** [Hook10/courseproject#27]
https://github.com/Hook10/courseproject/blob/578614eb55d8c0f5e6db8665e73fbad50271c7db/src/main/java/action/actionImpl/PayInvoiceButtonAction.java#L40-L51
Многочисленные if - это не очень хороший способ сделать сложное разветвление. Оператор switch - немного лучше. Предопределённый Map с несколькими значениями (как у вас в action factory) - самый оптимальный.

**Comment by MaximChshelokov** [comment]
Так же советую подумать над нэймингом. В данном примере неочевидно, что хранится в переменной **data**. Следует выбирать говорящие названия, особенно это ценится при работе в большой команде.

**Comment by Hook10** [comment]
ок, исправлю. Спасибо за пояснения!

**Comment by Hook10** [comment]
Done
