### ISSUE TITLE
Если хотите сделать этот участок кода более логичным, предлагаю рассмотреть возможность вынесение метода showDataBySupplier в родительский класс

### ISSUE THREAD

**Issue by MaximChshelokov** [Hook10/courseproject#29]
https://github.com/Hook10/courseproject/blob/5544a77f32e0719c25d89aaa4dc97aac408860df/src/main/java/action/actionImpl/ShowWaterAction.java#L22
Таким образом вы избавитесь от статического метода (которые не рекомендуется использовать), а так же не будет нелогиченого обращения одного экшена к другому.

**Comment by Hook10** [comment]
Максим, а можно я пока оставлю как есть?

**Comment by MaximChshelokov** [comment]
Хорошо, просто учтите, что в реальных проектах подобное не допускается.
