### ISSUE TITLE
Рекомендуется создавать приватный конструктор в классах, которые не подразумевают создание объектов

### ISSUE THREAD

**Issue by MaximChshelokov** [Hook10/courseproject#3]
https://github.com/Hook10/courseproject/blob/f3e771c41c3a440cc1a426b5cc414207eedd9040/src/main/java/constants/TariffConstants.java#L3

https://github.com/Hook10/courseproject/blob/f3e771c41c3a440cc1a426b5cc414207eedd9040/src/main/java/constants/ActionConstants.java#L3

**Comment by Hook10** [comment]
Done
