### ISSUE TITLE
Комментарии, не несущие дополнительного смысла лучше удалить

### ISSUE THREAD

**Issue by MaximChshelokov** [Hook10/courseproject#4]
https://github.com/Hook10/courseproject/blob/f3e771c41c3a440cc1a426b5cc414207eedd9040/src/main/java/dao/BaseDAO.java#L8
https://github.com/Hook10/courseproject/blob/f3e771c41c3a440cc1a426b5cc414207eedd9040/src/main/java/dao/BaseDAO.java#L11
https://github.com/Hook10/courseproject/blob/f3e771c41c3a440cc1a426b5cc414207eedd9040/src/main/java/dao/BaseDAO.java#L16
https://github.com/Hook10/courseproject/blob/f3e771c41c3a440cc1a426b5cc414207eedd9040/src/main/java/dao/BaseDAO.java#L19

**Comment by Hook10** [comment]
Done
