### ISSUE TITLE
Лучше подменить checked exception на unchecked, тогда не придётся указывать его в сигнатуре метода 

### ISSUE THREAD

**Issue by MaximChshelokov** [Hook10/courseproject#5]
https://github.com/Hook10/courseproject/blob/f3e771c41c3a440cc1a426b5cc414207eedd9040/src/main/java/dao/BaseDAO.java#L17

**Comment by Hook10** [comment]
Done
![image](https://user-images.githubusercontent.com/59989767/86199702-9813e180-bb7c-11ea-91d8-d94fbd2e68bf.png)
