### ISSUE TITLE
Магические цифры и строки лучше заменить константами

### ISSUE THREAD

**Issue by MaximChshelokov** [Hook10/courseproject#6]
https://github.com/Hook10/courseproject/blob/f3e771c41c3a440cc1a426b5cc414207eedd9040/src/main/java/dao/impl/AdminDaoImpl.java#L34
https://github.com/Hook10/courseproject/blob/f3e771c41c3a440cc1a426b5cc414207eedd9040/src/main/java/dao/impl/AdminDaoImpl.java#L94
https://github.com/Hook10/courseproject/blob/f3e771c41c3a440cc1a426b5cc414207eedd9040/src/main/java/dao/impl/AdminDaoImpl.java#L109

**Comment by Hook10** [comment]
Done.
