### ISSUE TITLE
Избыточные SQLException рекомендуется убрать из сигнатуры методов (эти исключения обрабатываются внутри методов)

### ISSUE THREAD

**Issue by MaximChshelokov** [Hook10/courseproject#7]
https://github.com/Hook10/courseproject/blob/f3e771c41c3a440cc1a426b5cc414207eedd9040/src/main/java/dao/impl/AdminDaoImpl.java#L105
https://github.com/Hook10/courseproject/blob/f3e771c41c3a440cc1a426b5cc414207eedd9040/src/main/java/dao/impl/AdminDaoImpl.java#L29

**Comment by Hook10** [comment]
Готово
