### ISSUE TITLE
Предлагаю записать стектрейс в лог, вместо консоли

### ISSUE THREAD

**Issue by MaximChshelokov** [Hook10/courseproject#8]
https://github.com/Hook10/courseproject/blob/f3e771c41c3a440cc1a426b5cc414207eedd9040/src/main/java/dao/impl/AdminDaoImpl.java#L86
https://github.com/Hook10/courseproject/blob/f3e771c41c3a440cc1a426b5cc414207eedd9040/src/main/java/dao/impl/AdminDaoImpl.java#L117
https://github.com/Hook10/courseproject/blob/f3e771c41c3a440cc1a426b5cc414207eedd9040/src/main/java/dao/impl/AdminDaoImpl.java#L133

**Comment by MaximChshelokov** [comment]
https://github.com/Hook10/courseproject/blob/f3e771c41c3a440cc1a426b5cc414207eedd9040/src/main/java/action/actionImpl/CreateSupplierAction.java#L50

**Comment by Hook10** [comment]
Done
